apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: ingress
    repoURL: https://github.com/FerRory/argo-deployments.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
