apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: local-path-provisioner
  namespace: argocd
spec:
  destination:
    namespace: local-path-storage
    server: https://kubernetes.default.svc
  project: default
  source:
    path: rancher-local-path-provisioner
    repoURL: https://github.com/FerRory/argo-deployments.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
